-- =========================
-- Table: biz_laptop_management
-- =========================
CREATE TABLE public.biz_laptop_management
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(3) NULL,
    created_by          BIGINT       NULL,
    creator             VARCHAR(191) NULL,

    updated_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by          BIGINT       NULL,
    updater             VARCHAR(191) NULL,

    deleted_by          BIGINT       NULL,
    deleted_at          TIMESTAMP(3) NULL,

    laptop_code         VARCHAR(191) NULL,
    office_license      VARCHAR(191) NULL,
    microsoft_account   VARCHAR(191) NULL,
    product_id          VARCHAR(191) NULL,
    sku_id              VARCHAR(191) NULL,
    license_name        VARCHAR(191) NULL,
    license_description VARCHAR(191) NULL,
    beta_expiration     VARCHAR(191) NULL,
    license_status      VARCHAR(191) NULL,
    status              VARCHAR(191) NULL,
    remark              VARCHAR(191) NULL,

    -- Optional: emulate UNSIGNED (MySQL) with CHECK constraints
    CONSTRAINT chk_biz_laptop_management_id_nonneg CHECK (id >= 0),
    CONSTRAINT chk_biz_laptop_management_created_by_nonneg CHECK (created_by IS NULL OR created_by >= 0),
    CONSTRAINT chk_biz_laptop_management_updated_by_nonneg CHECK (updated_by IS NULL OR updated_by >= 0),
    CONSTRAINT chk_biz_laptop_management_deleted_by_nonneg CHECK (deleted_by IS NULL OR deleted_by >= 0)
);

-- =========================
-- Comments (PostgreSQL uses COMMENT ON)
-- =========================
COMMENT ON TABLE public.biz_laptop_management IS 'laptop管理';

COMMENT ON COLUMN public.biz_laptop_management.id IS 'id';
COMMENT ON COLUMN public.biz_laptop_management.created_at IS 'created_at';
COMMENT ON COLUMN public.biz_laptop_management.created_by IS 'created_by';
COMMENT ON COLUMN public.biz_laptop_management.creator IS 'creator';
COMMENT ON COLUMN public.biz_laptop_management.updated_at IS 'updated_at';
COMMENT ON COLUMN public.biz_laptop_management.updated_by IS 'updated_by';
COMMENT ON COLUMN public.biz_laptop_management.updater IS 'updater';
COMMENT ON COLUMN public.biz_laptop_management.deleted_by IS 'deleted_by';
COMMENT ON COLUMN public.biz_laptop_management.deleted_at IS 'deleted_at';

COMMENT ON COLUMN public.biz_laptop_management.laptop_code IS '番号';
COMMENT ON COLUMN public.biz_laptop_management.office_license IS 'ライセンスキー';
COMMENT ON COLUMN public.biz_laptop_management.microsoft_account IS 'Microsoft Account';
COMMENT ON COLUMN public.biz_laptop_management.product_id IS 'PRODUCT_ID';
COMMENT ON COLUMN public.biz_laptop_management.sku_id IS 'SKU_ID';
COMMENT ON COLUMN public.biz_laptop_management.license_name IS 'LICENSE_NAME';
COMMENT ON COLUMN public.biz_laptop_management.license_description IS 'LICENSE_DESCRIPTION';
COMMENT ON COLUMN public.biz_laptop_management.beta_expiration IS 'BETA_EXPIRATION';
COMMENT ON COLUMN public.biz_laptop_management.license_status IS 'LICENSE_STATUS';
COMMENT ON COLUMN public.biz_laptop_management.status IS 'status';
COMMENT ON COLUMN public.biz_laptop_management.remark IS 'remark';

-- =========================
-- MySQL: ON UPDATE CURRENT_TIMESTAMP(3)
-- PostgreSQL: trigger to auto-touch updated_at
-- =========================
CREATE OR REPLACE FUNCTION public.tg_set_updated_at()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP(3);
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_biz_laptop_management_set_updated_at ON public.biz_laptop_management;

CREATE TRIGGER trg_biz_laptop_management_set_updated_at
    BEFORE UPDATE
    ON public.biz_laptop_management
    FOR EACH ROW
EXECUTE FUNCTION public.tg_set_updated_at();
